### ISSUE TITLE
crossbuild-ng will fail when building GDB on FreeBSD-14

### ISSUE THREAD

**Issue by hywelandrews** [yaul-org/libyaul-build-scripts#7]
I don't think this is specifically an issue with the libyaul-build-scripts, and possibly should be fixed in crosstool-ng, but raising here as I don't have enough experience for what a root cause fix would be:

From FreeBSD 12.2+ (and possibly other platforms) anything using liblzma library will now require linking against libmd if the following functions are used: 
`lzma_sha256_init`
`lzma_sha256_update`
`lzma_sha256_finish`

When the build fails in crosstools-ng for `gdb` which has this dependency, but is missing linking to `-lmd` you will not be able to pass this flag when manually calling the make command to attempt a rebuild of gdb.

Instead, you can edit `.build/sh2eb-elf/build/build-gdb-cross/gdb/Makefile:193` -> `LIBLZMA = -llzma -lmd`

**Comment by ijacquez** [comment]
Could this be remedied with updating the `crosstool-ng` submodule? This possibly has been addressed already. Can you try?

**Comment by hywelandrews** [comment]
Unfortunately updating `crosstool-ng` to the latest commit `+aa6a6c3a34b3e2c5b094855e8d2b57a698457561` didn't resolve the issue, and the build still gets stuck when cross building GDB due to missing the `-lmd` flag when linking

**Comment by ijacquez** [comment]
Thanks for the update. I know that you found a solution already, but I'm not to keen on keeping a patch around. It's possible that we could just add a new config and pass the flag for just GDB. Another (better) solution is to just update the version found in the config files.

Regarding the `ld` warning, thank you! I will add that.
